version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: flux_postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: flux_dev
      POSTGRES_USER: flux
      POSTGRES_PASSWORD: flux_secret
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U flux -d flux_dev']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  redis:
    image: redis:7-alpine
    container_name: flux_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: >
      redis-server
      --requirepass redis_secret
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', 'redis_secret', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: development
    container_name: flux_api
    restart: unless-stopped
    ports:
      - '3001:3001'
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://flux:flux_secret@postgres:5432/flux_dev
      REDIS_URL: redis://:redis_secret@redis:6379
    volumes:
      - ./apps/api/src:/app/apps/api/src
      - ./packages:/app/packages
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      target: development
    container_name: flux_web
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    depends_on:
      - api

  mailhog:
    image: mailhog/mailhog:latest
    container_name: flux_mailhog
    restart: unless-stopped
    ports:
      - '1025:1025'
      - '8025:8025'
    logging:
      driver: none

  bull-board:
    image: deadly0/bull-board:latest
    container_name: flux_bull_board
    restart: unless-stopped
    ports:
      - '3002:3000'
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_secret
    depends_on:
      redis:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
