export enum ErrorCode {
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  PLAN_LIMIT_REACHED = 'PLAN_LIMIT_REACHED',
  TENANT_NOT_FOUND = 'TENANT_NOT_FOUND',
  INVALID_TOKEN = 'INVALID_TOKEN',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  CNPJ_ALREADY_EXISTS = 'CNPJ_ALREADY_EXISTS',
  INVITE_EXPIRED = 'INVITE_EXPIRED',
  INVOICE_DUPLICATE = 'INVOICE_DUPLICATE',
  TAX_CALCULATION_ERROR = 'TAX_CALCULATION_ERROR',
}
