export enum PlanType {
  FREE = 'FREE',
  STARTER = 'STARTER',
  PROFESSIONAL = 'PROFESSIONAL',
  ENTERPRISE = 'ENTERPRISE',
}

export const PLAN_LIMITS = {
  FREE: {
    maxUsersPerTenant: 2,
    maxTransactionsPerMonth: 100,
    maxBankAccounts: 1,
    maxSuppliersTotal: 50,
    maxInvoicesPerMonth: 10,
    hasAiInsights: false,
    hasAutomationRules: false,
    hasRecurring: false,
    hasExport: false,
    hasTaxModule: false,
    hasBankReconciliation: false,
    hasApiAccess: false,
  },
  STARTER: {
    maxUsersPerTenant: 5,
    maxTransactionsPerMonth: 1000,
    maxBankAccounts: 3,
    maxSuppliersTotal: 500,
    maxInvoicesPerMonth: 100,
    hasAiInsights: false,
    hasAutomationRules: true,
    hasRecurring: true,
    hasExport: true,
    hasTaxModule: true,
    hasBankReconciliation: true,
    hasApiAccess: false,
  },
  PROFESSIONAL: {
    maxUsersPerTenant: 20,
    maxTransactionsPerMonth: Infinity,
    maxBankAccounts: Infinity,
    maxSuppliersTotal: Infinity,
    maxInvoicesPerMonth: Infinity,
    hasAiInsights: true,
    hasAutomationRules: true,
    hasRecurring: true,
    hasExport: true,
    hasTaxModule: true,
    hasBankReconciliation: true,
    hasApiAccess: true,
  },
  ENTERPRISE: {
    maxUsersPerTenant: Infinity,
    maxTransactionsPerMonth: Infinity,
    maxBankAccounts: Infinity,
    maxSuppliersTotal: Infinity,
    maxInvoicesPerMonth: Infinity,
    hasAiInsights: true,
    hasAutomationRules: true,
    hasRecurring: true,
    hasExport: true,
    hasTaxModule: true,
    hasBankReconciliation: true,
    hasApiAccess: true,
  },
} as const;

export type PlanLimits = (typeof PLAN_LIMITS)[PlanType];
